services:
  cockroach:
    image: cockroachdb/cockroach:v23.2.0
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - crdbdata:/cockroach/cockroach-data
volumes:
  crdbdata:
